name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get timestamp
        id: get-timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t singtown-registry.cn-shenzhen.cr.aliyuncs.com/singtown-ai/singtown-ai-keras-classification-training:${{ env.TIMESTAMP }} .

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: singtown-registry.cn-shenzhen.cr.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker image to ACR
        run: docker push singtown-registry.cn-shenzhen.cr.aliyuncs.com/singtown-ai/singtown-ai-keras-classification-training:${{ env.TIMESTAMP }}
